In [2]:
import numpy as np
z = np.zeros(3)
z

array([0., 0., 0.])

In [4]:
type(z[0])

numpy.float64

In [9]:
z = np.empty(5)
z

array([ 1.  ,  2.75,  6.  , 10.75, 17.  ])

In [7]:
z = np.array([10, 20, 30])
z

array([10, 20, 30])